name: cuppa_mobile
description: A simple tea timer app for Android and iOS.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.8.5+54

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ^3.27.3

dependencies:
  app_settings: ^5.2.0
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  file_picker: ^8.3.1
  fl_chart: ^0.70.2
  flex_color_picker: ^3.7.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^4.1.0
  in_app_review: ^2.0.10
  intelligence: ^0.1.0
  intl: ^0.19.0
  package_info_plus: ^8.1.4
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  quick_actions: ^1.1.0
  region_settings: ^1.2.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.1
  showcaseview: ^4.0.1
  sliver_tools: ^0.2.12
  sqflite: ^2.4.1
  transitioned_indexed_stack: ^1.0.2
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.10

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.14.0

patrol:
  app_name: Cuppa
  android:
    package_name: com.nathanatos.Cuppa
  ios:
    bundle_id: com.nathanatos.Cuppa

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/
    - langs/

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. Note: the `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
